[package]
name = 'didcomm-rust'
version = '0.1.0'
authors = ['Vyacheslav Gudkov <vyacheslav.gudkov@dsr-corporation.com>']
edition = '2018'

[dependencies]
anyhow = '1.0'
base64 = '0.13'
async-trait = '0.1'
thiserror = '1.0'
serde_json = '1.0'
serde-enum-str = '0.1'
sha2 = '0.9'

[dependencies.serde]
version = '1.0'
features = ['derive']

[dependencies.askar-crypto]
version = '0.2'
features = ['std']
[dev-dependencies.tokio]
version = '1.9'
features = [
    'rt',
    'macros',
]
